export const galleryPageData = {
  bannerData: {
    title: "Explore our <i>Gallery</i>",
    image: "/contact-bg.jpg",
  },

  gallerySection: {
    title: "Stay above the clouds",
    link: {
      label: "Check Availability",
      href: "#",
    },

    galleryImages: [
      { src: "/new-img/home/dji_082240.webp", alt: "All" },
      { src: "/new-img/home/dji_141926.webp", alt: "All" },
      { src: "/new-img/home/dji_195646.webp", alt: "All" },
      { src: "/new-img/home/dji_200058.webp", alt: "All" },
      { src: "/new-img/home/dji_20260624.webp", alt: "All" },
      { src: "/new-img/home/dji_fly_20260622.webp", alt: "All" },
      { src: "/new-img/home/_DSC0332.webp", alt: "All" },
      { src: "/new-img/home/_DSC0700.webp", alt: "All" },
      { src: "/new-img/home/_DSC0718.webp", alt: "All" },
      { src: "/new-img/home/_DSC0721.webp", alt: "All" },
      { src: "/new-img/home/_DSC0848.webp", alt: "All" },
      { src: "/new-img/home/_DSC0854.webp", alt: "All" },
      { src: "/new-img/home/_DSC1172.webp", alt: "All" },
      { src: "/new-img/home/_DSC1190-Edit.webp", alt: "All" },

      { src: "/new-img/_DSC0342.webp", alt: "All" },
      { src: "/new-img/_DSC0374.webp", alt: "All" },
      { src: "/new-img/_DSC0461.webp", alt: "All" },
      { src: "/new-img/_DSC0467.webp", alt: "All" },
      { src: "/new-img/_DSC0515.webp", alt: "All" },
      { src: "/new-img/_DSC0530.webp", alt: "All" },
      { src: "/new-img/_DSC0571.webp", alt: "All" },
      { src: "/new-img/_DSC0605.webp", alt: "All" },
      { src: "/new-img/_DSC0902.webp", alt: "All" },
      { src: "/new-img/_DSC1118.webp", alt: "All" },
      { src: "/new-img/_DSC1123.webp", alt: "All" },
      { src: "/new-img/_DSC1172.webp", alt: "All" },
      { src: "/new-img/_DSC1229.webp", alt: "All" },
      { src: "/new-img/_DSC1239.webp", alt: "All" },

      { src: "/wellness/_DSC0365.webp", alt: "All" },
      { src: "/wellness/_DSC0383.webp", alt: "All" },
      { src: "/wellness/_DSC0395.webp", alt: "All" },
      { src: "/wellness/_DSC0398.webp", alt: "All" },
      { src: "/wellness/_DSC0401.webp", alt: "All" },
      { src: "/wellness/_DSC0413.webp", alt: "All" },
      { src: "/wellness/_DSC0431.webp", alt: "All" },
      { src: "/wellness/_DSC0485.webp", alt: "All" },
      { src: "/wellness/_DSC0506.webp", alt: "All" },
      { src: "/wellness/_DSC0512.webp", alt: "All" },
      //   { src: "/gallery/gallery1.jpg", alt: "ALL" },
      // { src: "/gallery/view1.jpg",alt:"All" },
      // { src: "/gallery/view2.webp",alt:"All" },
      // { src: "/gallery/view3.jpg",alt:"All" },
      // { src: "/gallery/view4.jpg",alt:"All" },
      // { src: "/gallery/view5.jpg",alt:"All" },
      // { src: "/gallery/view6.jpg",alt:"All" },
      // { src: "/gallery/view7.jpeg",alt:"All" },
      // { src: "/gallery/view8.jpg",alt:"All" },
      // { src: "/gallery/view9.jpeg",alt:"All" },
      // { src: "/gallery/view10.jpeg",alt:"All" },
      // { src: "/gallery/view11.jpg",alt:"All" },
      // { src: "/gallery/view12.webp",alt:"All" },

      // { src: "/gallery/yoga1.jpg",alt:"All" },
      // { src: "/gallery/yoga2.webp",alt:"All" },
      // { src: "/gallery/yoga3.webp",alt:"All" },
      // { src: "/gallery/yoga4.JPG",alt:"All" },
      // { src: "/gallery/yoga5.jpg",alt:"All" },
      // { src: "/gallery/yoga6.webp",alt:"All" },
      // { src: "/gallery/yoga7.webp",alt:"All" },

      // { src: "/gallery/food1.jpeg",alt:"All" },
      // { src: "/gallery/food2.webp",alt:"All" },
      // { src: "/gallery/food3.jpg",alt:"All" },
      // { src: "/gallery/food4.jpg",alt:"All" },
      // { src: "/gallery/food5.webp",alt:"All" },
      // { src: "/gallery/food6.jpg",alt:"All" },

      // { src: "/gallery/room1.jpg",alt:"All" },
      // { src: "/gallery/room2.webp",alt:"All" },
      // { src: "/gallery/room3.jpg",alt:"All" },
      // { src: "/gallery/room4.jpg",alt:"All" },
      // { src: "/gallery/room5.webp",alt:"All" },
      // { src: "/gallery/room6.jpg",alt:"All" },
      // { src: "/gallery/room7.webp",alt:"All" },

      //   { src: "/gallery/gallery2.jpg", alt: "ALL" },
      //   { src: "/gallery/gallery3.jpg", alt: "ALL" },
    ],
  },
};
